/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
    kotlin("jvm") version "2.0.0-Beta5"
}

kotlin {
    jvmToolchain(17)
}

dependencies {
    api(libs.org.jetbrains.kotlin.kotlin.stdlib)
    api(project(":antlr5-core-runtime"))
}

description = "ANTLR 5 Kotlin Runtime"
