/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.jetbrains.kotlin.kotlin.stdlib)
    testImplementation(libs.org.antlr.st4)
    testImplementation(project(":antlr5-runtime-testsuite"))
    testImplementation(project(":antlr5-tool"))
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.params)
    testImplementation(libs.org.jetbrains.kotlin.kotlin.test)
    testImplementation(project(":antlr5-kotlin-runtime"))
}

description = "ANTLR 5 Tool Tests"
