/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.codehaus.plexus.plexus.compiler.api)
    api(libs.org.sonatype.plexus.plexus.build.api)
    api(project(":antlr5-tool"))
    api(libs.org.slf4j.slf4j.api)
    api(libs.org.slf4j.slf4j.simple)
    testImplementation(libs.junit.junit)
    testImplementation(libs.io.takari.maven.plugins.takari.plugin.testing)
    testImplementation(libs.org.apache.maven.maven.compat)
    compileOnly(libs.org.apache.maven.maven.plugin.api)
    compileOnly(libs.org.apache.maven.plugin.tools.maven.plugin.annotations)
    compileOnly(libs.org.apache.maven.maven.core)
    compileOnly(libs.org.codehaus.plexus.plexus.utils)
}

description = "ANTLR 5 Maven plugin"
