/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
    antlr
}

dependencies {
    antlr("org.antlr:antlr:3.5.3")
    api(project(":antlr5-core-runtime"))
    api(project(":antlr5-java-runtime"))
    api(libs.org.antlr.antlr.runtime)
    api(libs.org.antlr.st4)
    api(libs.org.abego.treelayout.org.abego.treelayout.core)
    api(libs.com.ibm.icu.icu4j)
}

description = "ANTLR 5 Tool"
