/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.openjdk.jol.jol.core)
    api(libs.org.jetbrains.kotlin.kotlin.stdlib)
    runtimeOnly(libs.org.jetbrains.kotlin.kotlin.compiler)
    testImplementation(libs.org.antlr.st4)
    testImplementation(project(":antlr5-tool"))
    testImplementation(project(":antlr5-java-runtime"))
    testImplementation(project(":antlr5-kotlin-runtime"))
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
    testImplementation(libs.org.glassfish.javax.json)
    testImplementation(libs.org.jetbrains.kotlin.kotlin.test)
}

description = "ANTLR 5 Runtime Tests"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
