/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
    kotlin("jvm") version "2.0.0-Beta5"
}

kotlin {
    jvmToolchain(17)
}

dependencies {
    api(libs.org.jetbrains.kotlin.kotlin.stdlib)
    testImplementation(libs.org.jetbrains.kotlin.kotlin.test)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
}

description = "ANTLR 5 Core Runtime"
